"""Pydantic data models for Document Tree, Provenance, and Verification."""

from backend.models.document import (
    BoundingBox,
    Clause,
    DocumentTree,
    PageData,
    ParsingStatus,
    TextBlock,
    TextSpan,
)
from backend.models.extraction import (
    CandidateExtractionResult,
    CandidateFact,
    ExtractionStatus,
    ExtractionSummary,
    MatchQuality,
    ProvenancedValue,
    ResolutionMethod,
    StructuredAgreement,
    StructuredAgreementResult,
    ValueQualifier,
)
from backend.models.verification import (
    AtomicClaim,
    ClaimSource,
    ClaimTag,
    ClaimVerificationMetadata,
    DocumentVerificationResult,
    RefusalCategory,
    VerificationResult,
    VerificationStatus,
    VerificationSummary,
)
from backend.models.qa import (
    AnswerStatus,
    EvidenceCitation,
    QARequest,
    QAResponse,
    QuestionType,
    RetrievalMetadata,
    RetrievalMethod,
)

__all__ = [
    "BoundingBox",
    "TextSpan",
    "TextBlock",
    "PageData",
    "Clause",
    "DocumentTree",
    "ParsingStatus",
    "ClaimTag",
    "AtomicClaim",
    "VerificationResult",
    "VerificationStatus",
    "RefusalCategory",
    "ClaimSource",
    "ClaimVerificationMetadata",
    "VerificationSummary",
    "DocumentVerificationResult",
    "CandidateFact",
    "CandidateExtractionResult",
    "ExtractionStatus",
    "ExtractionSummary",
    "MatchQuality",
    "ProvenancedValue",
    "ResolutionMethod",
    "StructuredAgreement",
    "StructuredAgreementResult",
    "ValueQualifier",
    "QuestionType",
    "AnswerStatus",
    "RetrievalMethod",
    "EvidenceCitation",
    "RetrievalMetadata",
    "QARequest",
    "QAResponse",
]

